language: python
python:
- 3.6
install:
- pip install codecov
- pip install -U tox-travis
script: tox
after_success:
- codecov
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: davidemoro
  password:
    secure: xM5CR6WoHDlvR8gq7kxlPcrW4KwIHsogdVwFZXB2UNR7h35GufuLsIVd6tuYaGRUJowJA59PxasccduBjMxRwpRIVUq/bEhenGno01wVgR/J6yPfaTiMIxZgOiqhJoeJinOWt3xsUZE5LhWlEIwBFoKpRROetMg46t0Dy0YA1qyhmtn30fNWBlhgIoxtk+V7dS1d6SzFSzKP5Hk1ZnA+xwp2GKtzSIWDkiy+7sIwvZ4bmHCQ6PQQYJy738zebEPoBQWB1JmORbJNbmNaPX3q5AN2ET8XtxHvYyvfdBMlb4fBomCRQtEUgS21On4ayYdOGRZExdyevF2glsJEbCMMXzuzK8BM/FjlTEtKaJslFzUh6vjQA6U2sA05on8bL55HzCOPiWYOxjEV8cwHlArkX2iLwlvTmMP8qpHJNtZJm2c0WxxxPiHIshdJf24XwWfodKnGmCKj2+ldJdPTVbED06s2IWFsr6cgStes/Hxn0lGL1TkUL/SWOJTN7tbjH6VQ9rqxLXuAEjyJLNRa68fVM/nrwB3m6kOk163G/lv/GhZNNdD5tkaeg49I3Ln37AWZl2Q0Phsco4bZU6H/eMU/PIXalucVjc9/J85JYpUI8FXazP4terD7lyPNcH4dMzmoKHnYijMYr3tDqHLr3jv4jdHPeLuFapvY6lJWkimKx/o=
  on:
    tags: true
    repo: davidemoro/play_requests
    python: 3.6
